CommonRequest request

---

CommonResponse response

string udcu_fw_ver
string udcu_hw_ver
string udcu_build_time

string ddcu_fw_ver
string ddcu_hw_ver
string ddcu_build_time

string safedcu_fw_ver
string safedcu_hw_ver
string safedcu_build_time
