CommonRequest request

# 从站序号 1 2  3
uint8 dcu_type

# can通信通道 1-左臂，左腿   2-右臂，右腿  3-头，腰
uint8 can_channel

# can通信id
uint8 can_id

# payload len
uint8 payload_len

# payload
uint8[] request_payload
---

CommonResponse response

# 从站序号 1 2  3
uint8 dcu_type

# can通信通道 1-左臂，左腿   2-右臂，右腿  3-头，腰
uint8 can_channel

# can通信id
uint8 can_id

# payload len
uint8 payload_len

# payload
uint8[] response_payload