# 灯带控制服务
CommonRequest request

# 灯带模式
uint8 led_strip_mode

## led_strip_mode: 灯带模式枚举
uint8 LED_GREEN_FLOW = 1 
uint8 LED_RAINBOW = 2   
uint8 LED_DANCING = 3    
uint8 LED_TWINKLE = 4 
uint8 LED_TAIL_INCREASE = 5 
uint8 LED_TAIL_DECREASE = 6   
uint8 LED_FOUR_TO_TWO_LEGS = 7    
uint8 LED_TWO_TO_FOUR_LEGS = 8 
uint8 LED_START_UP = 9 
uint8 LED_DISPLAY_CHARGING = 10   
uint8 LED_DISPLAY_FAULT = 11    
uint8 LED_DISPLAY_25_LOW_BATTERY = 12 
uint8 LED_DISPLAY_15_LOW_BATTERY = 13 
uint8 LED_DISPLAY_POWER_OFF = 14   
uint8 LED_DISPLAY_POWER_ON = 15    
uint8 LED_WHITE_FLOW = 16 
uint8 LED_WHITE_ON = 17 
---

CommonResponse response
uint16 result   #设置是否成功
