# 舵机同步控制服务
CommonRequest request

# 位置
uint8 position

## position: 舵机位置枚举
uint8 UNKNOWN = 0   # 未知
uint8 QUAD_POSITION = 1    # 四足形态
uint8 BIPED_POSITION = 2   # 双足形态

---

CommonResponse response
uint16 result   #设置是否成功
