# 此接口是播放全身动作接口

# 请求头
RequestHeader header

# 全身动作名称
McMotion motion

# onnx 模型绝对路径
string model

# 资源绝对路径，比如轨迹参考
string resource

# 是否打断(给后面animation接口合并预留)
bool interrupt

# 动作运行时间，0代表立刻运行，单位: ms (UNIX时间)
uint64 play_timestamp

---

# 响应头
CommonResponse response
