uint8 value

# 默认值，如果不填就是默认值，播放nlg时会使用配置的主语言
uint8 LANGUAGE_TYPE_UNDEFINED = 0

# 中文
uint8 LANGUAGE_TYPE_ZH = 1

# 英文
uint8 LANGUAGE_TYPE_EN = 2

# 阿拉伯语
uint8 LANGUAGE_TYPE_AR = 3

# 德语
uint8 LANGUAGE_TYPE_DE = 4

# 西班牙语
uint8 LANGUAGE_TYPE_ES = 5

# 法语
uint8 LANGUAGE_TYPE_FR = 6

# 日语
uint8 LANGUAGE_TYPE_JA = 7

# 韩语
uint8 LANGUAGE_TYPE_KO = 8

# 俄语
uint8 LANGUAGE_TYPE_RU = 9

# 泰语
uint8 LANGUAGE_TYPE_TH = 10
